version: "3.9"

services:
  # https://hub.docker.com/_/mysql
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      # DB Login Info
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  # https://hub.docker.com/_/mysql
  mysql-db:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # DB Login Info
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    ports:
      - 3306:3306
  # https://hub.docker.com/_/microsoft-mssql-server
  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server
    environment:
      # DB Login Info
      # MSSQL requires complex password.
      SA_PASSWORD: Pa55w0rd!  # Username: sa
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
