version: "3.9"

services:
  # https://hub.docker.com/_/postgres
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      # postgresql://postgres:Pa55w0rd!@localhost:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55w0rd!
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  # https://hub.docker.com/_/mysql
  mysql-db:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      # mysql://root:Passw0rd!@localhost:3306/mysql
      MYSQL_ROOT_PASSWORD: Pa55w0rd!
    ports:
      - 3306:3306
  # https://hub.docker.com/_/microsoft-mssql-server
  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server
    environment:
      # mssql://sa:Pa55w0rd!@localhost:1433/msdb?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes
      # No initial custom DB parameter.
      SA_PASSWORD: Pa55w0rd!
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
